
[2021-05-01 14:50:40] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 187, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
TypeError: embed_browser() takes 3 positional arguments but 5 were given


[2021-05-01 14:51:48] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 293, in OnClose
    if not self.browser:
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-01 14:52:22] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 187, in on_button_pressed
    self.embed_browser(start,end)
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 243, in embed_browser
    gmap.scatter(lat,lng,color=['blue', 'orange'])
NameError: name 'lat' is not defined


[2021-05-01 14:54:00] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 187, in on_button_pressed
    self.embed_browser(start,end)
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 244, in embed_browser
    gmap.plot(*path,edge_width=7,color='red')
UnboundLocalError: local variable 'path' referenced before assignment


[2021-05-01 14:55:23] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 187, in on_button_pressed
    self.embed_browser(start,end)
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 245, in embed_browser
    gmap.plot(*path,edge_width=7,color='red')
NameError: name 'path' is not defined


[2021-05-01 14:55:38] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 187, in on_button_pressed
    self.embed_browser(start,end)
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 246, in embed_browser
    gmap.draw("map.html")
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1050, in draw
    self._write_html(w)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1121, in _write_html
    self.write_points(w, color_cache)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1187, in write_points
    self.write_point(w, point[0], point[1], point[2], point[3], point[4], color_cache, point[5], point[6], point[7]) # TODO: Not maintainable.
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1235, in write_point
    marker = _Marker(_format_LatLng(lat, lng, precision), name=marker_name, title=title, label=label, icon=marker_icon.name, draggable=draggable)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 52, in _format_LatLng
    return 'new google.maps.LatLng(%.*f, %.*f)' % (precision, lat, precision, lng)
TypeError: must be real number, not str


[2021-05-01 14:56:30] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 187, in on_button_pressed
    self.embed_browser(start,end)
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 246, in embed_browser
    gmap.draw("map.html")
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1050, in draw
    self._write_html(w)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1121, in _write_html
    self.write_points(w, color_cache)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1187, in write_points
    self.write_point(w, point[0], point[1], point[2], point[3], point[4], color_cache, point[5], point[6], point[7]) # TODO: Not maintainable.
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1235, in write_point
    marker = _Marker(_format_LatLng(lat, lng, precision), name=marker_name, title=title, label=label, icon=marker_icon.name, draggable=draggable)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 52, in _format_LatLng
    return 'new google.maps.LatLng(%.*f, %.*f)' % (precision, lat, precision, lng)
TypeError: must be real number, not str


[2021-05-01 14:58:13] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 187, in on_button_pressed
    self.embed_browser(start,end)
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 246, in embed_browser
    gmap.draw("map.html")
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1050, in draw
    self._write_html(w)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1121, in _write_html
    self.write_points(w, color_cache)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1187, in write_points
    self.write_point(w, point[0], point[1], point[2], point[3], point[4], color_cache, point[5], point[6], point[7]) # TODO: Not maintainable.
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1235, in write_point
    marker = _Marker(_format_LatLng(lat, lng, precision), name=marker_name, title=title, label=label, icon=marker_icon.name, draggable=draggable)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 52, in _format_LatLng
    return 'new google.maps.LatLng(%.*f, %.*f)' % (precision, lat, precision, lng)
TypeError: must be real number, not str


[2021-05-01 14:59:08] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 187, in on_button_pressed
    self.embed_browser(start,end)
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 246, in embed_browser
    gmap.draw("map.html")
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1050, in draw
    self._write_html(w)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1121, in _write_html
    self.write_points(w, color_cache)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1187, in write_points
    self.write_point(w, point[0], point[1], point[2], point[3], point[4], color_cache, point[5], point[6], point[7]) # TODO: Not maintainable.
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1235, in write_point
    marker = _Marker(_format_LatLng(lat, lng, precision), name=marker_name, title=title, label=label, icon=marker_icon.name, draggable=draggable)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 52, in _format_LatLng
    return 'new google.maps.LatLng(%.*f, %.*f)' % (precision, lat, precision, lng)
TypeError: must be real number, not str


[2021-05-01 15:01:27] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 187, in on_button_pressed
    self.embed_browser(start,end)
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 246, in embed_browser
    gmap.draw("map.html")
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1050, in draw
    self._write_html(w)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1121, in _write_html
    self.write_points(w, color_cache)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1187, in write_points
    self.write_point(w, point[0], point[1], point[2], point[3], point[4], color_cache, point[5], point[6], point[7]) # TODO: Not maintainable.
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 1235, in write_point
    marker = _Marker(_format_LatLng(lat, lng, precision), name=marker_name, title=title, label=label, icon=marker_icon.name, draggable=draggable)
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 52, in _format_LatLng
    return 'new google.maps.LatLng(%.*f, %.*f)' % (precision, lat, precision, lng)
TypeError: must be real number, not str


[2021-05-01 15:11:05] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 187, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 245, in embed_browser
    gmap.plot(*path,edge_width=7,color='red')
UnboundLocalError: local variable 'path' referenced before assignment


[2021-05-01 15:23:27] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 306, in OnClose
    if not self.browser:
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-01 15:40:22] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 313, in OnClose
    if not self.browser:
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-01 15:43:40] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 320, in OnClose
    if not self.browser:
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-01 15:53:41] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 192, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 233, in embed_browser
    if self.wheelChair is False:
AttributeError: 'MainFrame' object has no attribute 'wheelChair'


[2021-05-01 15:54:50] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 316, in OnSize
    self.browser.NotifyMoveOrResizeStarted()
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-01 16:19:31] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 363, in OnClose
    if not self.browser:
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-01 17:03:46] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 407, in OnInit
    self.initialize()
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 415, in initialize
    frame = MainFrame()
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 163, in __init__
    self.embed_browser()
TypeError: embed_browser() missing 4 required positional arguments: 'start_lat', 'end_lat', 'start_lng', and 'end_lng'


[2021-05-01 17:04:51] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 350, in OnSize
    self.browser.NotifyMoveOrResizeStarted()
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-01 17:05:03] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 363, in OnClose
    if not self.browser:
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-01 18:05:21] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 363, in OnClose
    if not self.browser:
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-01 18:14:01] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 192, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 313, in embed_browser
    gmap.plot(*path,edge_width=7,color='red')
UnboundLocalError: local variable 'path' referenced before assignment


[2021-05-01 18:14:34] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 192, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 313, in embed_browser
    gmap.plot(*path,edge_width=7,color='red')
UnboundLocalError: local variable 'path' referenced before assignment


[2021-05-01 18:25:41] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 192, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 313, in embed_browser
    gmap.plot(*path,edge_width=7,color='red')
UnboundLocalError: local variable 'path' referenced before assignment


[2021-05-01 18:26:20] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 224, in on_enter
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 313, in embed_browser
    gmap.plot(*path,edge_width=7,color='red')
UnboundLocalError: local variable 'path' referenced before assignment


[2021-05-01 18:29:33] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 192, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 313, in embed_browser
    gmap.plot(*path,edge_width=7,color='red')
UnboundLocalError: local variable 'path' referenced before assignment


[2021-05-01 18:31:37] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 192, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 313, in embed_browser
    gmap.plot(*path,edge_width=7,color='red')
UnboundLocalError: local variable 'path' referenced before assignment


[2021-05-01 18:33:12] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 192, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 313, in embed_browser
    gmap.plot(*path,edge_width=7,color='red')
UnboundLocalError: local variable 'path' referenced before assignment


[2021-05-01 19:05:31] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 370, in OnClose
    if not self.browser:
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-01 19:06:45] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 370, in OnClose
    if not self.browser:
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-01 19:39:22] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 251, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 365, in embed_browser
    gmap.plot(*path,edge_width=7,color='red')
TypeError: plot() got multiple values for argument 'color'


[2021-05-01 19:40:15] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 251, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 365, in embed_browser
    gmap.plot(*path,edge_width=7)
TypeError: plot() takes from 3 to 5 positional arguments but 8 were given


[2021-05-01 19:54:30] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 251, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 370, in embed_browser
    gmap.plot(*path,edge_width=7)
UnboundLocalError: local variable 'path' referenced before assignment


[2021-05-01 20:00:59] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 251, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 370, in embed_browser
    gmap.plot(*path,edge_width=7)
UnboundLocalError: local variable 'path' referenced before assignment


[2021-05-01 20:03:13] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 251, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 370, in embed_browser
    gmap.plot(*path,edge_width=7)
UnboundLocalError: local variable 'path' referenced before assignment


[2021-05-01 20:06:05] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 251, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 370, in embed_browser
    gmap.plot(*path,edge_width=7)
UnboundLocalError: local variable 'path' referenced before assignment


[2021-05-01 20:07:32] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 251, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 370, in embed_browser
    gmap.plot(*path,edge_width=7)
UnboundLocalError: local variable 'path' referenced before assignment


[2021-05-01 21:56:53] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 422, in OnClose
    if not self.browser:
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-01 22:36:45] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22copy.py", line 303, in OnClose
    if not self.browser:
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-01 22:37:39] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22copy.py", line 303, in OnClose
    if not self.browser:
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-01 22:38:58] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22copy.py", line 303, in OnClose
    if not self.browser:
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-01 22:42:01] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22copy.py", line 303, in OnClose
    if not self.browser:
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-01 22:43:53] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22copy.py", line 307, in OnClose
    if not self.browser:
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-01 22:56:51] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 423, in OnClose
    if not self.browser:
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-02 16:25:20] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 423, in OnClose
    if not self.browser:
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-02 16:41:56] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 423, in OnClose
    if not self.browser:
AttributeError: 'MainFrame' object has no attribute 'browser'


[2021-05-02 16:58:42] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 253, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 373, in embed_browser
    gmap.plot(*path,edge_width=7)
TypeError: plot() missing 2 required positional arguments: 'lats' and 'lngs'


[2021-05-02 17:00:06] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 253, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 373, in embed_browser
    gmap.plot(*path,edge_width=7)
TypeError: plot() missing 2 required positional arguments: 'lats' and 'lngs'


[2021-05-02 17:12:46] Traceback (most recent call last):
  File "c:\Users\ninte\Documents\School\Software I\Project\MapoMaticUI22.py", line 253, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
  File "c:\Users\ninte\Documents\School\Software I\Project\MapoMaticUI22.py", line 374, in embed_browser
    gmap.plot(*path,edge_width=7)
TypeError: plot() missing 2 required positional arguments: 'lats' and 'lngs'


[2021-05-02 17:18:33] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 469, in OnInit
    self.initialize()
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 477, in initialize
    frame = MainFrame()
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 226, in __init__
    self.embed_browser(35.65572618535371,35.657162786958885,-97.47124943368546,-97.47134177810977)
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 375, in embed_browser
    gmap.plot(*path,edge_width=7)
UnboundLocalError: local variable 'path' referenced before assignment


[2021-05-02 17:46:56] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 245, in on_button_pressed
    self.sizer_1.Remove(self.browser_panel)
TypeError: Sizer.Remove(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'Panel'
  overload 2: argument 1 has unexpected type 'Panel'


[2021-05-02 17:47:30] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 494, in OnInit
    self.initialize()
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 502, in initialize
    frame = MainFrame()
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 227, in __init__
    self.sizer_1.Remove(self.browser_panel)
TypeError: Sizer.Remove(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'Panel'
  overload 2: argument 1 has unexpected type 'Panel'


[2021-05-02 17:48:10] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 494, in OnInit
    self.initialize()
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 502, in initialize
    frame = MainFrame()
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 222, in __init__
    sizer_1.Remove(self.browser_panel)
TypeError: Sizer.Remove(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'Panel'
  overload 2: argument 1 has unexpected type 'Panel'


[2021-05-02 17:56:00] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 256, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 384, in embed_browser
    window_info.SetAsOffscreen(self.browser_panel.GetHandle(),
TypeError: SetAsOffscreen() takes exactly one argument (2 given)


[2021-05-02 18:02:56] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 238, in on_button_pressed
    wx.Frame.DestroyChildren()
TypeError: Window.DestroyChildren(): first argument of unbound method must have type 'Window'


[2021-05-02 18:12:48] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 491, in OnInit
    self.initialize()
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 499, in initialize
    frame = MainFrame()
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 219, in __init__
    self.embed2()
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 392, in embed2
    gmap = gmplot.GoogleMapPlotter.from_geocode(35.65788082545061, -97.47177522238063,17, apikey=apikey)
TypeError: from_geocode() got multiple values for argument 'apikey'


[2021-05-02 18:30:23] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 282, in on_enter
    wx.Frame.Refresh(self.browser_panel.GetHandle())
TypeError: Window.Refresh(): first argument of unbound method must have type 'Window'


[2021-05-02 18:37:56] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 522, in OnInit
    self.initialize()
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 530, in initialize
    frame = MainFrame()
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 222, in __init__
    self.Bind(wx.EVT_SEARCHCTRL_SEARCH_BTN, self.on_Search_Enter, self.text_ctrl__copy)
AttributeError: 'MainFrame' object has no attribute 'on_Search_Enter'


[2021-05-02 18:43:39] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 287, in on_enter
    wx.Frame.Refresh(self.browser_panel.GetHandle())
TypeError: Window.Refresh(): first argument of unbound method must have type 'Window'


[2021-05-02 18:45:51] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 252, in on_Search_Enter
    self.embed3(ucoBuildings[ucoBUilding])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 426, in embed3
    gmap.scatter(building[0],building[1],color=['blue', 'orange'])
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 689, in scatter
    if len(lats) != len(lngs):
TypeError: object of type 'float' has no len()


[2021-05-02 18:46:36] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 274, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
KeyError: ''


[2021-05-02 18:49:05] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 252, in on_Search_Enter
    self.embed3(ucoBuildings[ucoBUilding])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 426, in embed3
    gmap.scatter(35.65563899390924, -97.47097476725821,color=['blue', 'orange'])
  File "C:\Python3\lib\site-packages\gmplot\gmplot.py", line 689, in scatter
    if len(lats) != len(lngs):
TypeError: object of type 'float' has no len()


[2021-05-02 18:52:34] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 252, in on_Search_Enter
    self.embed3(ucoBuildings[ucoBUilding])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 426, in embed3
    gmap.marker(building[0],building[1],'cyan',ucoBuildings[building],'N')
KeyError: (35.65572618535371, -97.47124943368546)


[2021-05-02 18:56:44] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 252, in on_Search_Enter
    self.embed3(ucoBuildings[ucoBUilding])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 426, in embed3
    gmap.marker(building[0],building[1],color='blue',title=ucoBuildings[building],label='N',info_window="<a href='https://www.uco.edu/'>UCO Website</a>")
KeyError: (35.65572618535371, -97.47124943368546)


[2021-05-02 19:09:30] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 274, in on_button_pressed
    self.embed_browser(ucoBuildings[start][0],ucoBuildings[end][0],ucoBuildings[start][1],ucoBuildings[end][1])
KeyError: ''


[2021-05-02 19:09:39] Traceback (most recent call last):
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 252, in on_Search_Enter
    self.embed3(ucoBuildings[ucoBUilding])
  File "c:/Users/ninte/Documents/School/Software I/Project/MapoMaticUI22.py", line 426, in embed3
    gmap.marker(building[0],building[1],color='blue',title=ucoBuildings.keys(0),label='N',info_window="<a href='https://www.uco.edu/'>UCO Website</a>")
TypeError: keys() takes no arguments (1 given)

